### PR TITLE
initial functionality regarding requirements

### PR DESCRIPTION
**Pull request by alex-zr**
Implemented

1. List all the possible moves on the board
2. Implement the ability for White and Black to make moves via the CLI
3. Detect when the game is over via checkmate

Added tests

### CODE REVIEW

**Comment by IRomanchenko** [comment]
Functionality:
1) `list` command implemented.
2) `move` command implemented
3) check-mate - partial.
False check-mate on:
* move c2 c3
* move d7 d6
* move d1 a4

**Comment by IRomanchenko** [comment]
Code quality:
There are bugs and some code parts are hard to read. Significant amount of duplicated code.

**Comment by IRomanchenko** [comment]
Tests:
Limited test coverage for piece movements.
No tests for `list` command.

**Comment by ArkadiiSavenkov** [comment]
Game
Program doesn’t check possible attack to king after moving piece.
move e2 e4
move e7 e5
move d1 h5
List
And we can see, that program shows f7 f6 and f7 f5 as possible movement, but it is false. But, frankly speaking, the program prevent launch such commands
 
2. Program processes checkmate, but (and I have never seen this before) doesn’t deny performing ‘list’ and ‘move’ command after checkmate. Moreover, after checkmate, the winner can continue moving their pieces. And he can repeat ‘move’ command several times. And it is possible remove checkmate (we can move back attacking piece ), and after that the game can continue, as usual. So we can set a lot of checkmates in one game
 
3. Big plus - I see that program doesn’t allow King to approach closer than 2 step to opp. King.
 
Code
I don’t like code style of this candidate. For example, I am not happy with lengthy ‘if’ (Piece.java - 75-95 lines). Other ugly  place is in Pawn.java - candidate repeated the same logic for white and black.
 
Conclusion
I think that we can try to work with this candidate. I feel that he can improve himself.

**Pull request closed without merging**
